name: Android Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 python3-dev \
            ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
            libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl \
            libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev \
            libffi-dev uuid-dev libffi8 autopoint autoconf automake libtool
      - name: Install Buildozer
        run: pip install --upgrade buildozer cython==0.29.33
      - name: Accept Android SDK Licenses
        run: |
          yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;35.0.0"
      - name: Build with Buildozer
        run: buildozer android debug
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-debug
          path: bin/*.apk
